DROP TABLE  JAVAWCBANK;
DROP SEQUENCE ACCOUNT_ID_SEQ

CREATE TABLE JAVAWCBANK
(
ACCOUNT_ID NUMBER(10)PRIMARY KEY,
NAME VARCHAR2(30)NOT NULL,
USERNAME VARCHAR2(20)UNIQUE,
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL_ID VARCHAR2(30) UNIQUE,
AMOUNT NUMBER(10) NOT NULL,
ADDRESS VARCHAR2(50)
);

CREATE SEQUENCE ACCOUNT_ID_SEQ
MINVALUE 0
MAXVALUE 999999
START WITH 201400
INCREMENT BY 1;

INSERT INTO JAVAWCBANK (ACCOUNT_ID,NAME,USERNAME,PASSWORD,EMAIL_ID,AMOUNT,ADDRESS)
VALUES (ACCOUNT_ID_SEQ.NEXTVAL,'HARSHIT', 'ACHARYA','HA017','HARSHIT@GMAIL.COM','1000','DAVANGERE');
